version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"  # Exposer le port 27017 pour la connexion à MongoDB
    volumes:
      - ./database:/data/db  # Persister les données de MongoDB localement

  backend:
    build: ./server
    container_name: flask-backend
    restart: always
    ports:
      - "5000:5000"  # Exposer le port 5000 pour l'application Flask
    depends_on:
      - mongodb  # Lancer MongoDB avant le backend
    environment:
      DB_URI: mongodb://admin:password@mongodb:27017/nom_de_ta_base  # URL de connexion MongoDB
