version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./bdd:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    container_name: flask_app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
