services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

  backend:
    build: ./server
    container_name: flask-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://admin:password@mongodb:27017/nom_de_ta_base
